%YAML:1.0 # need to specify the file type at the top!

cam0:
  T_imu_cam:
    - [0.0, 0.0, 1.0, 0.0]
    - [-1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0]
  distortion_model: radtan
  intrinsics: [320,320,320,240]
  resolution: [640, 480]
  timeshift_cam_imu: 0.0  # タイムシフトをリセット